FROM    archlinux AS stage1
LABEL   maintainer="ANSELME Containers <thiago@anselme.com.br>"
WORKDIR /app

RUN     pacman -Sy; \
        pacman -S --noconfirm ruby-irb;

COPY app/ .


FROM    alpine AS stage2
WORKDIR /app
COPY    --from=stage1 /app .
RUN     apk add --update ruby
CMD ["ruby", "app.rb"]
# FROM gcr.io/distroless/static-debian11 AS stage2
# COPY --from=stage1 /home/c/app/ /
# ENTRYPOINT ["./main"]