# FROM        openjdk:17  AS stage1
# WORKDIR     /app
# COPY        /app .

FROM        alpine:3.11
WORKDIR     /app
COPY        /app .
RUN         apk add --update openjdk11
CMD         ["java","app.java"]


