version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    container_name: CSharpApp
    networks:
      - net
  mysql:
    image: mysql:5.7  
    container_name: sqldb
    networks:
      - net
    volumes:
      - /home/wp/wpdb:/var/lib/mysql 
    environment:
      - MYSQL_DATABASE=answordpress 
      - MYSQL_USER=anselme
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD='1' 

networks:
  net:
    driver: bridge

