FROM alpine:3.15 AS stage1
LABEL maintainer="ANSELME Containers <thiago@anselme.com.br>"

RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
WORKDIR /home/csharp/app
VOLUME /home/csharp/app

COPY app/ .
#RUN gcc main.c -static -o main

# FROM gcr.io/distroless/static-debian11 AS stage2
# COPY --from=stage1 /home/c/app/ /
# ENTRYPOINT ["./main"]

ENTRYPOINT ["sh"]