FROM alpine:3.15 AS stage1
LABEL maintainer="ANSELME Containers <thiago@anselme.com.br>"

RUN apk add rust
WORKDIR /home/rust/app
VOLUME /home/rust/app

COPY app/ .
RUN rustc main.rs

FROM alpine:3.15 AS stage2
RUN apk add libgcc
COPY --from=stage1 /home/rust/app/ /
ENTRYPOINT ["./main"]