FROM        node:12.18.1
#ENV         NODE_ENV=production
WORKDIR     /app
VOLUME      /app

RUN         npm install
RUN         npm install -g nodemon

EXPOSE      80
#ENTRYPOINT ["nodemon", "app.js" ]
CMD [ "bash" ]
