FROM alpine:3.15 AS stage1
LABEL maintainer="ANSELME Containers <thiago@anselme.com.br>"

RUN apk add build-base
WORKDIR /home/c/app
VOLUME /home/c/app

COPY app/ .
RUN gcc main.c -static -o main

FROM gcr.io/distroless/static-debian11 AS stage2
COPY --from=stage1 /home/c/app/ /
ENTRYPOINT ["./main"]