FROM alpine:latest AS stage1
LABEL maintainer="ANSELME Containers <thiago@anselme.com.br>"

WORKDIR /app
COPY    /app .

RUN     apk update; \ 
        apk --update add erlang && rm -rf /var/cache/apk/*
RUN     erlc app.erl
CMD     ["erl", "-noshell", "-s", "app" ,"start" ,"-s" ,"init", "stop"]
